name: Docker Compose
description: Run any CI step in isolated Docker containers using Docker Compose
author: https://github.com/buildkite
requirements:
  - docker
  - docker-compose
configuration:
  properties:
    run:
      type: string
    build:
      type: [ string, array ]
      minimum: 1
    push:
      type: [ string, array ]
      minimum: 1
    ansi:
      type: boolean
    args:
      type: [ string, array ]
      minimum: 1
    build-alias:
      type: [ string, array ]
      minimum: 1
    buildkit:
      type: boolean
    cache-from:
      type: [ string, array ]
      minimum: 1
    cli-version:
      type: string
      enum:
        - 1
        - 2
    command:
      type: array
    config:
      type: [ string, array ]
      minimum: 1
    dependencies:
      type: boolean
    entrypoint:
      type: string
    env:
      type: [ string, array ]
      minimum: 1
    environment:
      type: [ string, array ]
      minimum: 1
    expand-volume-vars:
      type: boolean
    image-repository:
      type: string
    image-name:
      type: [ string, array ]
    leave-volumes:
      type: boolean
    mount-buildkite-agent:
      type: boolean
    mount-ssh-agent:
      type: boolean
    mount-checkout:
      type: [ boolean, string ]
    no-cache:
      type: boolean
    propagate-environment:
      type: boolean
    propagate-uid-gid:
      type: boolean
    pull:
      type: [ string, array ]
      minimum: 1
    pull-retries:
      type: integer
    push-retries:
      type: integer
    rm:
      type: boolean
    service-ports:
      type: boolean
    skip-checkout:
      type: boolean
    skip-pull:
      type: boolean
    ssh:
      type: boolean
    secrets:
      type: array
      items:
        type: string
    target:
      type: string
    tty:
      type: boolean
    upload-container-logs:
      type: string
    use-aliases:
      type: boolean
    verbose:
      type: boolean
    volumes:
      type: [ string, array ]
      minimum: 1
    workdir:
      type: string
  anyOf:
    - required:
      - run
    - required:
      - build
    - required:
      - push
  additionalProperties: false
  dependencies:
    ansi: [ run ]
    buildkit: [ build ]
    cache-from: [ build ]
    dependencies: [ run ]
    env: [ run ]
    environment: [ run ]
    expand-volume-vars: [ volumes ]
    image-repository: [ build ]
    image-name: [ build ]
    leave-volumes: [ run ]
    mount-buildkite-agent: [ run ]
    mount-checkout: [ run ]
    propagate-uid-gid: [ run ]
    pull: [ run ]
    push-retries: [ push ]
    skip-pull: [ run ]
    secrets: [ buildkit, build ]
    ssh: [ buildkit ]
    target: [ build ]
    tty: [ run ]
    use-aliases: [ run ]
    user: [ run ]
    volumes: [ run ]
    wait: [ run ]
    workdir: [ run ]
