name: Docker Compose
description: Run any CI step in isolated Docker containers using Docker Compose
author: https://github.com/buildkite
requirements:
  - docker
  - docker-compose
configuration:
  properties:
    run:
      type: string
    build:
      type: [string, array]
      minimum: 1
    push:
      type: [string, array]
      minimum: 1

    ansi:
      type: boolean
    args:
      type: [ string, array ]
      minimum: 1
    build-alias:
      type: [ string, array ]
      minimum: 1
    builder:
      type: object
      properties:
        bootstrap:
          type: boolean
        create:
          type: boolean
        debug:
          type: boolean
        driver:
          type: string
          enum: [ "docker-container", "kubernetes", "remote" ]
        driver-opt:
          type: string
        keep-daemon:
          type: boolean
        keep-state:
          type: boolean
        name:
          type: string
        platform:
          type: string
        remote-address:
          type: string
        remove:
          type: boolean
        use:
          type: boolean
      additionalProperties: false
    build-labels:
      type: [ string, array ]
      minimum: 1
    build-parallel:
      type: boolean
    buildkit:
      type: boolean
    buildkit-inline-cache:
      type: boolean
    cache-from:
      type: [ string, array ]
      minimum: 1
    cache-to:
      type: [ string, array ]
      minimum: 1
    cli-version:
      oneOf:
        - type: string
          enum: [ "1", "2" ]
        - type: integer
          enum: [ 1, 2 ]
    collapse-logs:
      type: boolean
    command:
      type: array
    compatibility:
      type: boolean
    config:
      type: [ string, array ]
      minimum: 1
    dependencies:
      type: boolean
    entrypoint:
      type: string
    env:
      type: [ string, array ]
      minimum: 1
    environment:
      type: [ string, array ]
      minimum: 1
    env-propagation-list:
      type: string
    expand-volume-vars:
      type: boolean
    graceful-shutdown:
      type: boolean
    leave-volumes:
      type: boolean
    mount-buildkite-agent:
      type: boolean
    mount-ssh-agent:
      type: [ boolean, string ]
    mount-checkout:
      type: [ boolean, string ]
    no-cache:
      type: boolean
    pre-run-dependencies:
      type: boolean
    prebuilt-image-namespace:
      type: string
    progress:
      type: string
      enum: [ "auto", "tty", "plain", "json", "quiet" ]
    propagate-environment:
      type: boolean
    propagate-uid-gid:
      type: boolean
    pull:
      type: [ string, array ]
      minimum: 1
    pull-retries:
      type: integer
    push-retries:
      type: integer
    quiet-pull:
      type: boolean
    require-prebuild:
      type: boolean
    rm:
      type: boolean
    run-image:
      type: string
    run-labels:
      type: boolean
    service-ports:
      type: boolean
    shell:
      type: [ boolean, array ]
    skip-checkout:
      type: boolean
    skip-pull:
      type: boolean
    ssh:
      type: [ boolean, string ]
    target:
      type: string
    tty:
      type: boolean
    upload-container-logs:
      type: string
      enum: [ "always", "never", "on-error" ]
    use-aliases:
      type: boolean
    user:
      type: string
    verbose:
      type: boolean
    volumes:
      type: [ string, array ]
      minimum: 1
    wait:
      type: boolean
    with-dependencies:
      type: boolean
    workdir:
      type: string
  anyOf:
    - required:
      - run
    - required:
      - build
    - required:
      - push
  additionalProperties: false
  dependencies:
    ansi: [ run ]
    args: [ build ]
    build-alias: [ push ]
    build-labels: [ build ]
    build-parallel: [ build ]
    buildkit: [ build ]
    buildkit-inline-cache: [ build ]
    cache-from: [ build ]
    cache-to: [ build ]
    command: [ run ]
    dependencies: [ run ]
    entrypoint: [ run ]
    env: [ run ]
    env-propagation-list: [ run ]
    environment: [ run ]
    expand-volume-vars: [ volumes ]
    graceful-shutdown: [ run ]
    leave-volumes: [ run ]
    mount-buildkite-agent: [ run ]
    mount-checkout: [ run ]
    mount-ssh-agent: [ run ]
    no-cache: [ build, run ]
    pre-run-dependencies: [ run ]
    progress: [ build, push, run ]
    propagate-environment: [ run ]
    propagate-uid-gid: [ run ]
    pull: [ run ]
    pull-retries: [ run ]
    push-retries: [ push ]
    quiet-pull: [ run ]
    require-prebuild: [ run ]
    rm: [ run ]
    run-image: [ run ]
    run-labels: [ run ]
    service-ports: [ run ]
    skip-pull: [ build, run ]
    shell: [ run ]
    ssh: [ build ]
    target: [ build ]
    tty: [ run ]
    upload-container-logs: [ run ]
    use-aliases: [ run ]
    user: [ run ]
    volumes: [ run ]
    wait: [ run ]
    with-dependencies: [ build ]
    workdir: [ run ]
