name: Docker Compose
description: Run any CI step in isolated Docker containers using Docker Compose
author: https://github.com/buildkite
requirements:
  - docker
  - docker-compose
configuration:
  properties:
    run:
      type: string
    build:
      type: [ string, array ]
      minimum: 1
    push:
      type: [ string, array ]
      minimum: 1
    pull:
      type: [ string, array ]
      minimum: 1
    config:
      type: [ string, array ]
      minimum: 1
    env:
      type: [ string, array ]
      minimum: 1
    environment:
      type: [ string, array ]
      minimum: 1
    args:
      type: [ string, array ]
      minimum: 1
    build-alias:
      type: [ string, array ]
      minimum: 1
    image-repository:
      type: string
    image-name:
      type: string
    pull-retries:
      type: integer
    push-retries:
      type: integer
    cache-from:
      type: [ string, array ]
      minimum: 1
    volumes:
      type: [ string, array ]
      minimum: 1
    command:
      type: array
    skip-checkout:
      type: boolean
    leave-volumes:
      type: boolean
    no-cache:
      type: boolean
    use-aliases:
      type: boolean
    tty:
      type: boolean
    dependencies:
      type: boolean
    ansi:
      type: boolean
    verbose:
      type: boolean
    workdir:
      type: string
    mount-buildkite-agent:
      type: boolean
  oneOf:
    - required:
      - run
    - required:
      - build
    - required:
      - push
  additionalProperties: false
  dependencies:
    pull: [ run ]
    image-repository: [ build ]
    image-name: [ build ]
    env: [ run ]
    environment: [ run ]
    pull-retries: [ build, run ]
    push-retries: [ push ]
    cache-from: [ build ]
    volumes: [ run ]
    leave-volumes: [ run ]
    no-cache: [ build ]
    use-aliases: [ run ]
    dependencies: [ run ]
    ansi: [ run ]
    tty: [ run ]
    workdir: [ run ]
    user: [ run ]
    mount-buildkite-agent: [ run ]
