name: Docker Compose
description: Run any CI step in isolated Docker containers using Docker Compose
author: https://github.com/buildkite
requirements:
  - docker
  - docker-compose
configuration:
  properties:
    run:
      type: string
    build:
      type: [string, array]
      minimum: 1
    push:
      type: [string, array]
      minimum: 1
    ansi:
      type: boolean
    args:
      type: [string, array]
      minimum: 1
    build-alias:
      type: [string, array]
      minimum: 1
    buildkit:
      type: boolean
    cache-from:
      type: [string, array]
      minimum: 1
    compatibility:
      type: boolean
    cli-version:
      oneOf:
        - type: string
          enum: ["1", "2"]
        - type: integer
          enum: [1, 2]
    command:
      type: array
    collapse-run-log-group:
      type: boolean
    config:
      type: [string, array]
      minimum: 1
    dependencies:
      type: boolean
    entrypoint:
      type: string
    env:
      type: [string, array]
      minimum: 1
    environment:
      type: [string, array]
      minimum: 1
    env-propagation-list:
      type: string
    expand-volume-vars:
      type: boolean
    image-repository:
      type: string
    image-name:
      type: [string, array]
    leave-volumes:
      type: boolean
    mount-buildkite-agent:
      type: boolean
    mount-ssh-agent:
      type: [boolean, string]
    mount-checkout:
      type: [boolean, string]
    no-cache:
      type: boolean
    pre-run-dependencies:
      type: boolean
    propagate-environment:
      type: boolean
    propagate-uid-gid:
      type: boolean
    pull:
      type: [string, array]
      minimum: 1
    pull-retries:
      type: integer
    push-retries:
      type: integer
    quiet-pull:
      type: boolean
    rm:
      type: boolean
    run-labels:
      type: boolean
    separator-cache-from:
      type: string
      minLength: 1
      maxLength: 1
    service-ports:
      type: boolean
    skip-checkout:
      type: boolean
    skip-pull:
      type: boolean
    ssh:
      type: [boolean, string]
    secrets:
      type: array
      items:
        type: string
    target:
      type: string
    tty:
      type: boolean
    upload-container-logs:
      type: string
    use-aliases:
      type: boolean
    verbose:
      type: boolean
    volumes:
      type: [string, array]
      minimum: 1
    workdir:
      type: string
    use-prior-image:
      type: boolean
  anyOf:
    - required:
        - run
    - required:
        - build
    - required:
        - push
  additionalProperties: false
  dependencies:
    ansi: [run]
    buildkit: [build]
    cache-from: [build]
    cache-from-separator: [cache-from]
    dependencies: [run]
    env: [run]
    environment: [run]
    expand-volume-vars: [volumes]
    image-repository: [build]
    image-name: [build]
    leave-volumes: [run]
    mount-buildkite-agent: [run]
    mount-checkout: [run]
    pre-run-dependencies: [run]
    propagate-uid-gid: [run]
    pull: [run]
    push-retries: [push]
    quiet-pull: [run]
    service-ports: [run]
    skip-pull: [build, run]
    secrets: [buildkit, build]
    ssh: [buildkit]
    target: [build]
    tty: [run]
    use-aliases: [run]
    user: [run]
    volumes: [run]
    wait: [run]
    workdir: [run]
    use-prior-image: [build]
