#!/bin/bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

build_driver="$(plugin_read_config BUILD_DRIVER "")"
valid_drivers="docker-container|kubernetes|remote"
if [[ "${build_driver}" =~ ^(${valid_drivers})$ ]]; then
    echo "~~~ :docker: Creating and Using Builder Instance with Driver: ${build_driver}"
    # Use Buildkite Job ID to create unique builder instance instance per Job
    # add prefix due constraint needing to start with a letter
    export BUILDER_INSTANCE_NAME="${build_driver}-${BUILDKITE_JOB_ID}"
    docker buildx create --driver "${build_driver}" --name "${BUILDER_INSTANCE_NAME}" --use --bootstrap
    export BUILD_DRIVER_INSTANCE=true
elif [[ -z "$build_driver"  ]]; then
    echo "~~~ :docker: Using Default Build Driver 'docker'"
else
    echo "+++ 🚨 Invalid driver: ${build_driver}"
    echo "Valid Drivers: ${valid_drivers//|/, }"
    exit 1
fi
