#!/bin/bash
set -ueo pipefail

if [[ -n "${PERSIST_REGISTRY:-}" ]]; then
  echo "~~~ Uploading test Docker registry data"
  tar -czf docker-registry.tar.gz tmp/registry
  buildkite-agent artifact upload docker-registry.tar.gz
fi
