#!/bin/bash
set -ueo pipefail

echo "~~~ Stopping test Docker registry"
docker container stop "docker-compose-plugin-registry-${BUILDKITE_STEP_ID}" && docker container rm -v "docker-compose-plugin-registry-${BUILDKITE_STEP_ID}"